// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoW8Oh6svZL86VUzC7UnA_VFb7m6GpQFs',
    appId: '1:190274162576:web:bf5ef7afd678e7ca55ad15',
    messagingSenderId: '190274162576',
    projectId: 'krainettest',
    authDomain: 'krainettest.firebaseapp.com',
    storageBucket: 'krainettest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-KJZ8ZUU32RG7p2jP3E1DTqh_ZuaRM6g',
    appId: '1:190274162576:android:2a5146d77f64ee5155ad15',
    messagingSenderId: '190274162576',
    projectId: 'krainettest',
    storageBucket: 'krainettest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9LHEziehYN3FRNVzC0HjygqrukoxAFKs',
    appId: '1:190274162576:ios:6b7d31b3171d1c6c55ad15',
    messagingSenderId: '190274162576',
    projectId: 'krainettest',
    storageBucket: 'krainettest.appspot.com',
    iosClientId: '190274162576-1ieosls6r7l1j80uqljglfmvvbee40kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.krainetTest',
  );
}
